embed_size : 256
log_std_min : -5
log_std_max : 2
epsilon : 0.2
actor_lr : 0.0003
critic_lr : 0.0003
baseline_coef : 0.25
value_coef : 0.5
seed : 0
n_epochs : 3
batch_size : 256
n_steps_in_environment : 10_000_000
n_steps_trajectory : 128
gamma : 0.99
lambda : 0.95
n_envs : 16
normalize : true
entropy_coef : 0.01